services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_service
    restart: unless-stopped
    networks:
      - database-network

  app:
    depends_on:
      - postgres
    restart: unless-stopped
    container_name: account-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_VERSION: "${SERVICE_VERSION}"
    volumes:
      - ./.env:/app/.env
    ports:
      - "${GATEWAY_PORT}:80" # Gateway mapped correctly
      - "${RPC_PORT}:8080"    # RPC mapped correctly
    env_file:
      - .env  # Automatically load environment variables from .env file
    healthcheck:
      test: curl -f http://localhost:${GATEWAY_PORT}/api/v1/account-service/healthz || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - database-network

networks:
  database-network:
    name: database-network