// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: account/v1/account_message.proto

package accountv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostStatus int32

const (
	PostStatus_Draft   PostStatus = 0
	PostStatus_Publish PostStatus = 1
	PostStatus_Trash   PostStatus = 2
)

// Enum value maps for PostStatus.
var (
	PostStatus_name = map[int32]string{
		0: "Draft",
		1: "Publish",
		2: "Trash",
	}
	PostStatus_value = map[string]int32{
		"Draft":   0,
		"Publish": 1,
		"Trash":   2,
	}
)

func (x PostStatus) Enum() *PostStatus {
	p := new(PostStatus)
	*p = x
	return p
}

func (x PostStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_account_v1_account_message_proto_enumTypes[0].Descriptor()
}

func (PostStatus) Type() protoreflect.EnumType {
	return &file_account_v1_account_message_proto_enumTypes[0]
}

func (x PostStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostStatus.Descriptor instead.
func (PostStatus) EnumDescriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{0}
}

type BadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Errors        map[string]string      `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadRequest) Reset() {
	*x = BadRequest{}
	mi := &file_account_v1_account_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadRequest) ProtoMessage() {}

func (x *BadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadRequest.ProtoReflect.Descriptor instead.
func (*BadRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{0}
}

func (x *BadRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BadRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BadRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BadRequest) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Unauthorized struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unauthorized) Reset() {
	*x = Unauthorized{}
	mi := &file_account_v1_account_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unauthorized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unauthorized) ProtoMessage() {}

func (x *Unauthorized) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unauthorized.ProtoReflect.Descriptor instead.
func (*Unauthorized) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{1}
}

func (x *Unauthorized) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Unauthorized) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Unauthorized) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Forbidden struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forbidden) Reset() {
	*x = Forbidden{}
	mi := &file_account_v1_account_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forbidden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forbidden) ProtoMessage() {}

func (x *Forbidden) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forbidden.ProtoReflect.Descriptor instead.
func (*Forbidden) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{2}
}

func (x *Forbidden) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Forbidden) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Forbidden) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotFound) Reset() {
	*x = NotFound{}
	mi := &file_account_v1_account_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFound) ProtoMessage() {}

func (x *NotFound) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFound.ProtoReflect.Descriptor instead.
func (*NotFound) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{3}
}

func (x *NotFound) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NotFound) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotFound) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_account_v1_account_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{4}
}

func (x *Conflict) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Conflict) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Conflict) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnprocessableEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnprocessableEntity) Reset() {
	*x = UnprocessableEntity{}
	mi := &file_account_v1_account_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnprocessableEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnprocessableEntity) ProtoMessage() {}

func (x *UnprocessableEntity) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnprocessableEntity.ProtoReflect.Descriptor instead.
func (*UnprocessableEntity) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{5}
}

func (x *UnprocessableEntity) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnprocessableEntity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnprocessableEntity) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InternalServerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalServerError) Reset() {
	*x = InternalServerError{}
	mi := &file_account_v1_account_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalServerError) ProtoMessage() {}

func (x *InternalServerError) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalServerError.ProtoReflect.Descriptor instead.
func (*InternalServerError) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{6}
}

func (x *InternalServerError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InternalServerError) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InternalServerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_account_v1_account_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{7}
}

func (x *CommonResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_account_v1_account_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{8}
}

func (x *Param) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_account_v1_account_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CitizenId     string                 `protobuf:"bytes,2,opt,name=citizen_id,json=citizenId,proto3" json:"citizen_id,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_v1_account_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetCitizenId() string {
	if x != nil {
		return x.CitizenId
	}
	return ""
}

func (x *CreateAccountRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Code          uint32                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CreateAccountResponse_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_v1_account_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{11}
}

func (x *CreateAccountResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateAccountResponse) GetData() *CreateAccountResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBalanceByAccountNumberResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Code          uint32                                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                                  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetBalanceByAccountNumberResponse_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceByAccountNumberResponse) Reset() {
	*x = GetBalanceByAccountNumberResponse{}
	mi := &file_account_v1_account_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceByAccountNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceByAccountNumberResponse) ProtoMessage() {}

func (x *GetBalanceByAccountNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceByAccountNumberResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceByAccountNumberResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{12}
}

func (x *GetBalanceByAccountNumberResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetBalanceByAccountNumberResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBalanceByAccountNumberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBalanceByAccountNumberResponse) GetData() *GetBalanceByAccountNumberResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type SavingBalanceRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	AccountNumber string                            `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Body          *SavingBalanceRequest_BodyRequest `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavingBalanceRequest) Reset() {
	*x = SavingBalanceRequest{}
	mi := &file_account_v1_account_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavingBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavingBalanceRequest) ProtoMessage() {}

func (x *SavingBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavingBalanceRequest.ProtoReflect.Descriptor instead.
func (*SavingBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{13}
}

func (x *SavingBalanceRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *SavingBalanceRequest) GetBody() *SavingBalanceRequest_BodyRequest {
	if x != nil {
		return x.Body
	}
	return nil
}

type WithdrawBalanceRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	AccountNumber string                              `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Body          *WithdrawBalanceRequest_BodyRequest `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawBalanceRequest) Reset() {
	*x = WithdrawBalanceRequest{}
	mi := &file_account_v1_account_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBalanceRequest) ProtoMessage() {}

func (x *WithdrawBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBalanceRequest.ProtoReflect.Descriptor instead.
func (*WithdrawBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{14}
}

func (x *WithdrawBalanceRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *WithdrawBalanceRequest) GetBody() *WithdrawBalanceRequest_BodyRequest {
	if x != nil {
		return x.Body
	}
	return nil
}

type CreateAccountResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CitizenId     string                 `protobuf:"bytes,2,opt,name=citizen_id,json=citizenId,proto3" json:"citizen_id,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance       float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse_Data) Reset() {
	*x = CreateAccountResponse_Data{}
	mi := &file_account_v1_account_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse_Data) ProtoMessage() {}

func (x *CreateAccountResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse_Data.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse_Data) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{11, 0}
}

func (x *CreateAccountResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountResponse_Data) GetCitizenId() string {
	if x != nil {
		return x.CitizenId
	}
	return ""
}

func (x *CreateAccountResponse_Data) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateAccountResponse_Data) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateAccountResponse_Data) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetBalanceByAccountNumberResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CitizenId     string                 `protobuf:"bytes,2,opt,name=citizen_id,json=citizenId,proto3" json:"citizen_id,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance       float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceByAccountNumberResponse_Data) Reset() {
	*x = GetBalanceByAccountNumberResponse_Data{}
	mi := &file_account_v1_account_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceByAccountNumberResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceByAccountNumberResponse_Data) ProtoMessage() {}

func (x *GetBalanceByAccountNumberResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceByAccountNumberResponse_Data.ProtoReflect.Descriptor instead.
func (*GetBalanceByAccountNumberResponse_Data) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{12, 0}
}

func (x *GetBalanceByAccountNumberResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBalanceByAccountNumberResponse_Data) GetCitizenId() string {
	if x != nil {
		return x.CitizenId
	}
	return ""
}

func (x *GetBalanceByAccountNumberResponse_Data) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetBalanceByAccountNumberResponse_Data) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *GetBalanceByAccountNumberResponse_Data) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type SavingBalanceRequest_BodyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavingBalanceRequest_BodyRequest) Reset() {
	*x = SavingBalanceRequest_BodyRequest{}
	mi := &file_account_v1_account_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavingBalanceRequest_BodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavingBalanceRequest_BodyRequest) ProtoMessage() {}

func (x *SavingBalanceRequest_BodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavingBalanceRequest_BodyRequest.ProtoReflect.Descriptor instead.
func (*SavingBalanceRequest_BodyRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{13, 0}
}

func (x *SavingBalanceRequest_BodyRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawBalanceRequest_BodyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawBalanceRequest_BodyRequest) Reset() {
	*x = WithdrawBalanceRequest_BodyRequest{}
	mi := &file_account_v1_account_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawBalanceRequest_BodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBalanceRequest_BodyRequest) ProtoMessage() {}

func (x *WithdrawBalanceRequest_BodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBalanceRequest_BodyRequest.ProtoReflect.Descriptor instead.
func (*WithdrawBalanceRequest_BodyRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_message_proto_rawDescGZIP(), []int{14, 0}
}

func (x *WithdrawBalanceRequest_BodyRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_account_v1_account_message_proto protoreflect.FileDescriptor

const file_account_v1_account_message_proto_rawDesc = "" +
	"\n" +
	" account/v1/account_message.proto\x12\n" +
	"account.v1\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa6\x02\n" +
	"\n" +
	"BadRequest\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"400\"R\x04code\x12*\n" +
	"\x06status\x18\x02 \x01(\tB\x12\x92A\x0fJ\r\"BAD REQUEST\"R\x06status\x12,\n" +
	"\amessage\x18\x03 \x01(\tB\x12\x92A\x0fJ\r\"Bad Request\"R\amessage\x12c\n" +
	"\x06errors\x18\x04 \x03(\v2\".account.v1.BadRequest.ErrorsEntryB'\x92A$J\"{\"field\": \"the field is required\"}R\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\fUnauthorized\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"401\"R\x04code\x12+\n" +
	"\x06status\x18\x02 \x01(\tB\x13\x92A\x10J\x0e\"UNAUTHORIZED\"R\x06status\x12-\n" +
	"\amessage\x18\x03 \x01(\tB\x13\x92A\x10J\x0e\"Unauthorized\"R\amessage\"\x99\x01\n" +
	"\tForbidden\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"403\"R\x04code\x12(\n" +
	"\x06status\x18\x02 \x01(\tB\x10\x92A\rJ\v\"FORBIDDEN\"R\x06status\x12B\n" +
	"\amessage\x18\x03 \x01(\tB(\x92A%J#\"You does not have correct access.\"R\amessage\"\x86\x01\n" +
	"\bNotFound\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"404\"R\x04code\x12(\n" +
	"\x06status\x18\x02 \x01(\tB\x10\x92A\rJ\v\"NOT FOUND\"R\x06status\x120\n" +
	"\amessage\x18\x03 \x01(\tB\x16\x92A\x13J\x11\"Item not found.\"R\amessage\"\x8a\x01\n" +
	"\bConflict\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"419\"R\x04code\x12'\n" +
	"\x06status\x18\x02 \x01(\tB\x0f\x92A\fJ\n" +
	"\"CONFLICT\"R\x06status\x125\n" +
	"\amessage\x18\x03 \x01(\tB\x1b\x92A\x18J\x16\"Item already exists.\"R\amessage\"\xa1\x01\n" +
	"\x13UnprocessableEntity\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"422\"R\x04code\x123\n" +
	"\x06status\x18\x02 \x01(\tB\x1b\x92A\x18J\x16\"UNPROCESSABLE ENTITY\"R\x06status\x125\n" +
	"\amessage\x18\x03 \x01(\tB\x1b\x92A\x18J\x16\"Unprocessable entity\"R\amessage\"\xa3\x01\n" +
	"\x13InternalServerError\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"500\"R\x04code\x124\n" +
	"\x06status\x18\x02 \x01(\tB\x1c\x92A\x19J\x17\"INTERNAL SERVER ERROR\"R\x06status\x126\n" +
	"\amessage\x18\x03 \x01(\tB\x1c\x92A\x19J\x17\"Internal Server Error\"R\amessage\"\x91\x01\n" +
	"\x0eCommonResponse\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"200\"R\x04code\x12!\n" +
	"\x06status\x18\x02 \x01(\tB\t\x92A\x06J\x04\"OK\"R\x06status\x12<\n" +
	"\amessage\x18\x03 \x01(\tB\"\x92A\x1fJ\x1d\"Message of common response.\"R\amessage\".\n" +
	"\x05Param\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\"G\n" +
	"\x13HealthCheckResponse\x120\n" +
	"\amessage\x18\x01 \x01(\tB\x16\x92A\x13J\x11\"Service Running\"R\amessage\"\xc2\x02\n" +
	"\x14CreateAccountRequest\x12#\n" +
	"\x04name\x18\x01 \x01(\tB\x0f\x92A\fJ\n" +
	"\"John Doe\"R\x04name\x126\n" +
	"\n" +
	"citizen_id\x18\x02 \x01(\tB\x17\x92A\x14J\x12\"1234567890123456\"R\tcitizenId\x12z\n" +
	"\x05phone\x18\x03 \x01(\tBd\x92Aa2O\"E.164 numbers format [+][country code][subscriber number including area code]\"J\x0e\"+62123456789\"R\x05phone:Q\x92AN\n" +
	"L*\x16Create Account Request2\x16Create Account Request\xd2\x01\x04name\xd2\x01\n" +
	"citizen_id\xd2\x01\x05phone\"\x98\x04\n" +
	"\x15CreateAccountResponse\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"200\"R\x04code\x12!\n" +
	"\x06status\x18\x02 \x01(\tB\t\x92A\x06J\x04\"OK\"R\x06status\x125\n" +
	"\amessage\x18\x03 \x01(\tB\x1b\x92A\x18J\x16\"Get balance success.\"R\amessage\x12:\n" +
	"\x04data\x18\x04 \x01(\v2&.account.v1.CreateAccountResponse.DataR\x04data\x1a\xc8\x02\n" +
	"\x04Data\x12#\n" +
	"\x04name\x18\x01 \x01(\tB\x0f\x92A\fJ\n" +
	"\"John Doe\"R\x04name\x126\n" +
	"\n" +
	"citizen_id\x18\x02 \x01(\tB\x17\x92A\x14J\x12\"1234567890123456\"R\tcitizenId\x12z\n" +
	"\x05phone\x18\x03 \x01(\tBd\x92Aa2O\"E.164 numbers format [+][country code][subscriber number including area code]\"J\x0e\"+62123456789\"R\x05phone\x12>\n" +
	"\x0eaccount_number\x18\x04 \x01(\tB\x17\x92A\x14J\x12\"1234567890123456\"R\raccountNumber\x12'\n" +
	"\abalance\x18\x05 \x01(\x01B\r\x92A\n" +
	"J\b\"100000\"R\abalance\"\xb0\x04\n" +
	"!GetBalanceByAccountNumberResponse\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"200\"R\x04code\x12!\n" +
	"\x06status\x18\x02 \x01(\tB\t\x92A\x06J\x04\"OK\"R\x06status\x125\n" +
	"\amessage\x18\x03 \x01(\tB\x1b\x92A\x18J\x16\"Get balance success.\"R\amessage\x12F\n" +
	"\x04data\x18\x04 \x01(\v22.account.v1.GetBalanceByAccountNumberResponse.DataR\x04data\x1a\xc8\x02\n" +
	"\x04Data\x12#\n" +
	"\x04name\x18\x01 \x01(\tB\x0f\x92A\fJ\n" +
	"\"John Doe\"R\x04name\x126\n" +
	"\n" +
	"citizen_id\x18\x02 \x01(\tB\x17\x92A\x14J\x12\"1234567890123456\"R\tcitizenId\x12z\n" +
	"\x05phone\x18\x03 \x01(\tBd\x92Aa2O\"E.164 numbers format [+][country code][subscriber number including area code]\"J\x0e\"+62123456789\"R\x05phone\x12>\n" +
	"\x0eaccount_number\x18\x04 \x01(\tB\x17\x92A\x14J\x12\"1234567890123456\"R\raccountNumber\x12'\n" +
	"\abalance\x18\x05 \x01(\x01B\r\x92A\n" +
	"J\b\"100000\"R\abalance\"\x9a\x02\n" +
	"\x14SavingBalanceRequest\x12<\n" +
	"\x0eaccount_number\x18\x01 \x01(\tB\x15\x92A\x12J\x10\"12345678901234\"R\raccountNumber\x12@\n" +
	"\x04body\x18\x02 \x01(\v2,.account.v1.SavingBalanceRequest.BodyRequestR\x04body\x1a3\n" +
	"\vBodyRequest\x12$\n" +
	"\x06amount\x18\x01 \x01(\x01B\f\x92A\tJ\a\"10000\"R\x06amount:M\x92AJ\n" +
	"H*\x16Saving Balance Request2\x16Saving Balance Request\xd2\x01\x0eaccount_number\xd2\x01\x04body\"\xa2\x02\n" +
	"\x16WithdrawBalanceRequest\x12<\n" +
	"\x0eaccount_number\x18\x01 \x01(\tB\x15\x92A\x12J\x10\"12345678901234\"R\raccountNumber\x12B\n" +
	"\x04body\x18\x02 \x01(\v2..account.v1.WithdrawBalanceRequest.BodyRequestR\x04body\x1a3\n" +
	"\vBodyRequest\x12$\n" +
	"\x06amount\x18\x01 \x01(\x01B\f\x92A\tJ\a\"10000\"R\x06amount:Q\x92AN\n" +
	"L*\x18Withdraw Balance Request2\x18Withdraw Balance Request\xd2\x01\x0eaccount_number\xd2\x01\x04body*/\n" +
	"\n" +
	"PostStatus\x12\t\n" +
	"\x05Draft\x10\x00\x12\v\n" +
	"\aPublish\x10\x01\x12\t\n" +
	"\x05Trash\x10\x02B@Z>github.com/Kkmikaze/account-service/proto/account/v1;accountv1b\x06proto3"

var (
	file_account_v1_account_message_proto_rawDescOnce sync.Once
	file_account_v1_account_message_proto_rawDescData []byte
)

func file_account_v1_account_message_proto_rawDescGZIP() []byte {
	file_account_v1_account_message_proto_rawDescOnce.Do(func() {
		file_account_v1_account_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_account_message_proto_rawDesc), len(file_account_v1_account_message_proto_rawDesc)))
	})
	return file_account_v1_account_message_proto_rawDescData
}

var file_account_v1_account_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_v1_account_message_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_account_v1_account_message_proto_goTypes = []any{
	(PostStatus)(0),                                // 0: account.v1.PostStatus
	(*BadRequest)(nil),                             // 1: account.v1.BadRequest
	(*Unauthorized)(nil),                           // 2: account.v1.Unauthorized
	(*Forbidden)(nil),                              // 3: account.v1.Forbidden
	(*NotFound)(nil),                               // 4: account.v1.NotFound
	(*Conflict)(nil),                               // 5: account.v1.Conflict
	(*UnprocessableEntity)(nil),                    // 6: account.v1.UnprocessableEntity
	(*InternalServerError)(nil),                    // 7: account.v1.InternalServerError
	(*CommonResponse)(nil),                         // 8: account.v1.CommonResponse
	(*Param)(nil),                                  // 9: account.v1.Param
	(*HealthCheckResponse)(nil),                    // 10: account.v1.HealthCheckResponse
	(*CreateAccountRequest)(nil),                   // 11: account.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),                  // 12: account.v1.CreateAccountResponse
	(*GetBalanceByAccountNumberResponse)(nil),      // 13: account.v1.GetBalanceByAccountNumberResponse
	(*SavingBalanceRequest)(nil),                   // 14: account.v1.SavingBalanceRequest
	(*WithdrawBalanceRequest)(nil),                 // 15: account.v1.WithdrawBalanceRequest
	nil,                                            // 16: account.v1.BadRequest.ErrorsEntry
	(*CreateAccountResponse_Data)(nil),             // 17: account.v1.CreateAccountResponse.Data
	(*GetBalanceByAccountNumberResponse_Data)(nil), // 18: account.v1.GetBalanceByAccountNumberResponse.Data
	(*SavingBalanceRequest_BodyRequest)(nil),       // 19: account.v1.SavingBalanceRequest.BodyRequest
	(*WithdrawBalanceRequest_BodyRequest)(nil),     // 20: account.v1.WithdrawBalanceRequest.BodyRequest
}
var file_account_v1_account_message_proto_depIdxs = []int32{
	16, // 0: account.v1.BadRequest.errors:type_name -> account.v1.BadRequest.ErrorsEntry
	17, // 1: account.v1.CreateAccountResponse.data:type_name -> account.v1.CreateAccountResponse.Data
	18, // 2: account.v1.GetBalanceByAccountNumberResponse.data:type_name -> account.v1.GetBalanceByAccountNumberResponse.Data
	19, // 3: account.v1.SavingBalanceRequest.body:type_name -> account.v1.SavingBalanceRequest.BodyRequest
	20, // 4: account.v1.WithdrawBalanceRequest.body:type_name -> account.v1.WithdrawBalanceRequest.BodyRequest
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_account_v1_account_message_proto_init() }
func file_account_v1_account_message_proto_init() {
	if File_account_v1_account_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_account_message_proto_rawDesc), len(file_account_v1_account_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_v1_account_message_proto_goTypes,
		DependencyIndexes: file_account_v1_account_message_proto_depIdxs,
		EnumInfos:         file_account_v1_account_message_proto_enumTypes,
		MessageInfos:      file_account_v1_account_message_proto_msgTypes,
	}.Build()
	File_account_v1_account_message_proto = out.File
	file_account_v1_account_message_proto_goTypes = nil
	file_account_v1_account_message_proto_depIdxs = nil
}
