// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: account/v1/account_service.proto

package accountv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_account_v1_account_service_proto protoreflect.FileDescriptor

const file_account_v1_account_service_proto_rawDesc = "" +
	"\n" +
	" account/v1/account_service.proto\x12\n" +
	"account.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a account/v1/account_message.proto2\x88\n" +
	"\n" +
	"\x0eAccountService\x12\xa5\x01\n" +
	"\fHealthzCheck\x12\x16.google.protobuf.Empty\x1a\x1f.account.v1.HealthCheckResponse\"\\\x92A2J0\n" +
	"\x03200\x12)\n" +
	"\x02OK\x12#\n" +
	"!\x1a\x1f.account.v1.HealthCheckResponse\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/account-service/healthz\x12\xfd\x01\n" +
	"\rCreateAccount\x12 .account.v1.CreateAccountRequest\x1a!.account.v1.CreateAccountResponse\"\xa6\x01\x92Ax\n" +
	"\aAccount\x12\x0eCreate Account\x1a)This API for create/register new account.J2\n" +
	"\x03200\x12+\n" +
	"\x02OK\x12%\n" +
	"#\x1a!.account.v1.CreateAccountResponse\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/account-service/accounts\x12\xb1\x02\n" +
	"\x19GetBalanceByAccountNumber\x12\x11.account.v1.Param\x1a-.account.v1.GetBalanceByAccountNumberResponse\"\xd1\x01\x92A\x94\x01\n" +
	"\aBalance\x12\x1dGet Balance By Account Number\x1a*This API for get balance by account numberJ>\n" +
	"\x03200\x127\n" +
	"\x02OK\x121\n" +
	"/\x1a-.account.v1.GetBalanceByAccountNumberResponse\x82\xd3\xe4\x93\x023\x121/api/v1/account-service/balances/{account_number}\x12\x86\x02\n" +
	"\rSavingBalance\x12 .account.v1.SavingBalanceRequest\x1a\x1a.account.v1.CommonResponse\"\xb6\x01\x92Av\n" +
	"\aBalance\x12\x0eSaving Balance\x1a.This API for saving balance by account number.J+\n" +
	"\x03200\x12$\n" +
	"\x02OK\x12\x1e\n" +
	"\x1c\x1a\x1a.account.v1.CommonResponse\x82\xd3\xe4\x93\x027:\x04body\x1a//api/v1/account-service/saving/{account_number}\x12\x90\x02\n" +
	"\x0fWithdrawBalance\x12\".account.v1.WithdrawBalanceRequest\x1a\x1a.account.v1.CommonResponse\"\xbc\x01\x92Az\n" +
	"\aBalance\x12\x10Withdraw Balance\x1a0This API for withdraw balance by account number.J+\n" +
	"\x03200\x12$\n" +
	"\x02OK\x12\x1e\n" +
	"\x1c\x1a\x1a.account.v1.CommonResponse\x82\xd3\xe4\x93\x029:\x04body\x1a1/api/v1/account-service/withdraw/{account_number}B\xd9\x03\x92A\x95\x03\x12\x19\n" +
	"\x0fAccount Service2\x06v1.0.0R0\n" +
	"\x03400\x12)\n" +
	"\vBad Request\x12\x1a\n" +
	"\x18\x1a\x16.account.v1.BadRequestR3\n" +
	"\x03401\x12,\n" +
	"\fUnauthorized\x12\x1c\n" +
	"\x1a\x1a\x18.account.v1.UnauthorizedR-\n" +
	"\x03403\x12&\n" +
	"\tForbidden\x12\x19\n" +
	"\x17\x1a\x15.account.v1.ForbiddenR,\n" +
	"\x03404\x12%\n" +
	"\tNot Found\x12\x18\n" +
	"\x16\x1a\x14.account.v1.NotFoundR+\n" +
	"\x03419\x12$\n" +
	"\bConflict\x12\x18\n" +
	"\x16\x1a\x14.account.v1.ConflictRB\n" +
	"\x03422\x12;\n" +
	"\x14Unprocessable Entity\x12#\n" +
	"!\x1a\x1f.account.v1.UnprocessableEntityRC\n" +
	"\x03500\x12<\n" +
	"\x15Internal Server Error\x12#\n" +
	"!\x1a\x1f.account.v1.InternalServerErrorZ>github.com/Kkmikaze/account-service/proto/account/v1;accountv1b\x06proto3"

var file_account_v1_account_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),                     // 0: google.protobuf.Empty
	(*CreateAccountRequest)(nil),              // 1: account.v1.CreateAccountRequest
	(*Param)(nil),                             // 2: account.v1.Param
	(*SavingBalanceRequest)(nil),              // 3: account.v1.SavingBalanceRequest
	(*WithdrawBalanceRequest)(nil),            // 4: account.v1.WithdrawBalanceRequest
	(*HealthCheckResponse)(nil),               // 5: account.v1.HealthCheckResponse
	(*CreateAccountResponse)(nil),             // 6: account.v1.CreateAccountResponse
	(*GetBalanceByAccountNumberResponse)(nil), // 7: account.v1.GetBalanceByAccountNumberResponse
	(*CommonResponse)(nil),                    // 8: account.v1.CommonResponse
}
var file_account_v1_account_service_proto_depIdxs = []int32{
	0, // 0: account.v1.AccountService.HealthzCheck:input_type -> google.protobuf.Empty
	1, // 1: account.v1.AccountService.CreateAccount:input_type -> account.v1.CreateAccountRequest
	2, // 2: account.v1.AccountService.GetBalanceByAccountNumber:input_type -> account.v1.Param
	3, // 3: account.v1.AccountService.SavingBalance:input_type -> account.v1.SavingBalanceRequest
	4, // 4: account.v1.AccountService.WithdrawBalance:input_type -> account.v1.WithdrawBalanceRequest
	5, // 5: account.v1.AccountService.HealthzCheck:output_type -> account.v1.HealthCheckResponse
	6, // 6: account.v1.AccountService.CreateAccount:output_type -> account.v1.CreateAccountResponse
	7, // 7: account.v1.AccountService.GetBalanceByAccountNumber:output_type -> account.v1.GetBalanceByAccountNumberResponse
	8, // 8: account.v1.AccountService.SavingBalance:output_type -> account.v1.CommonResponse
	8, // 9: account.v1.AccountService.WithdrawBalance:output_type -> account.v1.CommonResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_v1_account_service_proto_init() }
func file_account_v1_account_service_proto_init() {
	if File_account_v1_account_service_proto != nil {
		return
	}
	file_account_v1_account_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_account_service_proto_rawDesc), len(file_account_v1_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v1_account_service_proto_goTypes,
		DependencyIndexes: file_account_v1_account_service_proto_depIdxs,
	}.Build()
	File_account_v1_account_service_proto = out.File
	file_account_v1_account_service_proto_goTypes = nil
	file_account_v1_account_service_proto_depIdxs = nil
}
